name: Bump Flake Inputs
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.update.outputs.pull-request-number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty

    - name: Update Lockfile
      uses: DeterminateSystems/update-flake-lock@main
      id: update
      with:
        pr-title: ':package:(flake): bump'
        commit-msg: ':package:(flake): bump'
        token: ${{ secrets.GITHUB_TOKEN }}

  validate:
    needs: update
    if: needs.update.outputs.pr-number != ''
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR Branch
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ needs.update.outputs.pr-number }}/head
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty

    - name: Check Flake
      run: nix flake check --accept-flake-config

  merge:
    needs: [update, validate]
    if: needs.validate.result == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Merge PR
      run: gh pr merge ${{ needs.update.outputs.pr-number }} --squash --delete-branch --repo ${{ github.repository }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
